# -*- coding: utf-8 -*-

__author__ = 'Guilherme Castelao'
__email__ = 'guilherme@castelao.net'

from pkg_resources import DistributionNotFound, get_distribution

try:
    __version__ = get_distribution(__name__).version
except DistributionNotFound:
    try:
        from .version import version as __version__
    except ImportError:
        raise ImportError(
            "Failed to find (autogenerated) version.py. "
            "This might be because you are installing from GitHub's tarballs, "
            "use the PyPI ones."
        )


from oceansdb.woa import WOA
from oceansdb.etopo import ETOPO
from oceansdb.cars import CARS
#from WOA.woa import woa_profile
#from WOA.woa import woa_profile_from_dap
#from WOA.woa import woa_track_from_file
